repos:
  - repo: local
    hooks:
      - id: increment-patch-version
        name: Increment Patch Version
        entry: go run version.go patch
        language: golang
        pass_filenames: false
        always_run: true